[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.16"
auto_detect_solc = true
auto_detect_remappings = true
ffi = true
via_ir = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
bsc-testnet= "${BSCTEST_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
scroll = "${SEPOLIASCROLL_RPC_URL}"


[etherscan]
bsc-testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
