[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.16"
auto_detect_solc = true
auto_detect_remappings = false
ffi = true
via_ir = true
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
bsctest= "${BSCTEST_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
zkevm = "${ZKEVM_RPC_URL}"


[etherscan]
bsctest = { key = "${BSCSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
